name: Release Binaries

on: 
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ "windows" ]
        goarch: ["386", "amd64" ]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.19
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.17rc2
        binary_name: "vscode-winsta11er-$(matrix.goarch)"
