name: Release Binaries

on: 
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: Release
    runs-on: windows-latest
    strategy:
      matrix:
        goarch: ["386", "amd64", "arm64"]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.19
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://golang.org/dl/go1.17rc2.windows-amd64.zip"
